export const teamColors = {
    1: { // Atlanta Hawks
      primary: "#E03A3E",
      primaryContrastFont: "#fff",
      secondary: "#C1D32F",
      secondaryContrastFont: "#333",
      tertiary: "#26282A",
    },
    2: { // Boston Celtics
      primary: "#007A33",
      primaryContrastFont: "#fff",
      secondary: "#BA9653",
      secondaryContrastFont: "#fff",
      tertiary: "#963821",
    },
    3: { // Brooklyn Nets
      primary: "#000000",
      primaryContrastFont: "#fff",
      secondary: "#777D84",
      secondaryContrastFont: "#fff",
      tertiary: "#FFFFFF",
    },
    4: { // Charlotte Hornets
      primary: "#00788C",
      primaryContrastFont: "#fff",
      secondary: "#1D1160",
      secondaryContrastFont: "#fff",
      tertiary: "#A1A1A4",
    },
    5: { // Chicago Bulls
      primary: "#CE1141",
      primaryContrastFont: "#fff",
      secondary: "#000000",
      secondaryContrastFont: "#fff",
      tertiary: "#CE1141",
    },
    6: { // Cleveland Cavaliers
      primary: "#860038",
      primaryContrastFont: "#fff",
      secondary: "#041E42",
      secondaryContrastFont: "#fff",
      tertiary: "#FDBB30",
    },
    7: { // Dallas Mavericks
      primary: "#00538C",
      primaryContrastFont: "#fff",
      secondary: "#002B5E",
      secondaryContrastFont: "#fff",
      tertiary: "#B8C4CA",
    },
    8: { // Denver Nuggets
      primary: "#0E2240",
      primaryContrastFont: "#fff",
      secondary: "#FEC524",
      secondaryContrastFont: "#333",
      tertiary: "#8B2131",
    },
    9: { // Detroit Pistons
      primary: "#C8102E",
      primaryContrastFont: "#fff",
      secondary: "#1D42BA",
      secondaryContrastFont: "#fff",
      tertiary: "#BEC0C2",
    },
    10: { // Golden State Warriors
      primary: "#1D428A",
      primaryContrastFont: "#fff",
      secondary: "#FFC72C",
      secondaryContrastFont: "#333",
      tertiary: "#26282A",
    },
    11: { // Houston Rockets
      primary: "#CE1141",
      primaryContrastFont: "#fff",
      secondary: "#000000",
      secondaryContrastFont: "#fff",
      tertiary: "#C4CED4",
    },
    12: { // Indiana Pacers
      primary: "#002D62",
      primaryContrastFont: "#fff",
      secondary: "#FDBB30",
      secondaryContrastFont: "#333",
      tertiary: "#BEC0C2",
    },
    13: { // Los Angeles Clippers
      primary: "#C8102E",
      primaryContrastFont: "#fff",
      secondary: "#1D428A",
      secondaryContrastFont: "#fff",
      tertiary: "#BEC0C2",
    },
    14: { // Los Angeles Lakers
      primary: "#552583",
      primaryContrastFont: "#fff",
      secondary: "#FDB927",
      secondaryContrastFont: "#333",
      tertiary: "#000000",
    },
    15: { // Memphis Grizzlies
      primary: "#5D76A9",
      primaryContrastFont: "#fff",
      secondary: "#12173F",
      secondaryContrastFont: "#fff",
      tertiary: "#F5B112",
    },
    16: { // Miami Heat
      primary: "#98002E",
      primaryContrastFont: "#fff",
      secondary: "#F9A01B",
      secondaryContrastFont: "#333",
      tertiary: "#000000",
    },
    17: { // Milwaukee Bucks
      primary: "#00471B",
      primaryContrastFont: "#fff",
      secondary: "#EEE1C6",
      secondaryContrastFont: "#333",
      tertiary: "#0077C0",
    },
    18: { // Minnesota Timberwolves
      primary: "#236192",
      primaryContrastFont: "#fff",
      secondary: "#0C2340",
      secondaryContrastFont: "#fff",
      tertiary: "#78BE20",
    },
    19: { // New Orleans Pelicans
      primary: "#0C2340",
      primaryContrastFont: "#fff",
      secondary: "#C8102E",
      secondaryContrastFont: "#fff",
      tertiary: "#85714D",
    },
    20: { // New York Knicks
      primary: "#F58426",
      primaryContrastFont: "#fff",
      secondary: "#006BB6",
      secondaryContrastFont: "#fff",
      tertiary: "#BEC0C2",
    },
    21: { // Oklahoma City Thunder
      primary: "#007AC1",
      primaryContrastFont: "#fff",
      secondary: "#EF3B24",
      secondaryContrastFont: "#fff",
      tertiary: "#002D62",
    },
    22: { // Orlando Magic
      primary: "#0077C0",
      primaryContrastFont: "#fff",
      secondary: "#C4CED4",
      secondaryContrastFont: "#333",
      tertiary: "#000000",
    },
    23: { // Philadelphia 76ers
      primary: "#003DA5",
      primaryContrastFont: "#fff",
      secondary: "#D50032",
      secondaryContrastFont: "#fff",
      tertiary: "#002B5C",
    },
    24: { // Phoenix Suns
      primary: "#E56020",
      primaryContrastFont: "#fff",
      secondary: "#1D1160",
      secondaryContrastFont: "#fff",
      tertiary: "#000000",
    },
    25: { // Portland Trail Blazers
      primary: "#E03A3E",
      primaryContrastFont: "#fff",
      secondary: "#000000",
      secondaryContrastFont: "#fff",
      tertiary: "#E03A3E",
    },
    26: { // Sacramento Kings
      primary: "#5A2D81",
      primaryContrastFont: "#fff",
      secondary: "#63727A",
      secondaryContrastFont: "#fff",
      tertiary: "#000000",
    },
    27: { // San Antonio Spurs
      primary: "#000000",
      primaryContrastFont: "#fff",
      secondary: "#C4CED4",
      secondaryContrastFont: "#333",
      tertiary: "#8A8D8F",
    },
    28: { // Toronto Raptors
      primary: "#CE1141",
      primaryContrastFont: "#fff",
      secondary: "#000000",
      secondaryContrastFont: "#fff",
      tertiary: "#A1A1A4",
    },
    29: { // Utah Jazz
      primary: "#753bbd",
      primaryContrastFont: "#fff",
      secondary: "#00a9e0",
      secondaryContrastFont: "#fff",
      tertiary: "#6CAEDF",
    },
    30: { // Washington Wizards
      primary: "#002B5C",
      primaryContrastFont: "#fff",
      secondary: "#E31837",
      secondaryContrastFont: "#fff",
      tertiary: "#C4CED4",
    },
  };